### ISSUE TITLE
PyPy tests fail on Travis

### ISSUE THREAD

**Issue by onyxfish** [wireservice/agate#651]
Looks like a slugify dependency is screwing things up...

```
ERROR: Failure: ImportError (unable to load extension module '/home/travis/virtualenv/pypy-2.5.0/site-packages/_regex.pypy-25.so': /home/travis/virtualenv/pypy-2.5.0/site-packages/_regex.pypy-25.so: undefined symbol: PyLong_FromUnicode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/pypy-2.5.0/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/virtualenv/pypy-2.5.0/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/virtualenv/pypy-2.5.0/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/build/wireservice/agate/tests/test_columns.py", line 16, in <module>
    from agate import Table
  File "/home/travis/build/wireservice/agate/agate/__init__.py", line 5, in <module>
    from agate.aggregations import *
  File "/home/travis/build/wireservice/agate/agate/aggregations/__init__.py", line 22, in <module>
    from agate.aggregations.count import Count  # noqa
  File "/home/travis/build/wireservice/agate/agate/aggregations/count.py", line 5, in <module>
    from agate.utils import default
  File "/home/travis/build/wireservice/agate/agate/utils.py", line 13, in <module>
    from slugify import Slugify, UniqueSlugify
  File "/home/travis/virtualenv/pypy-2.5.0/site-packages/slugify/__init__.py", line 2, in <module>
    from slugify.main import Slugify, UniqueSlugify
  File "/home/travis/virtualenv/pypy-2.5.0/site-packages/slugify/main.py", line 6, in <module>
    import regex as re
  File "/home/travis/virtualenv/pypy-2.5.0/site-packages/regex.py", line 383, in <module>
    import _regex_core
  File "/home/travis/virtualenv/pypy-2.5.0/site-packages/_regex_core.py", line 21, in <module>
    import _regex
ImportError: unable to load extension module '/home/travis/virtualenv/pypy-2.5.0/site-packages/_regex.pypy-25.so': /home/travis/virtualenv/pypy-2.5.0/site-packages/_regex.pypy-25.so: undefined symbol: PyLong_FromUnicode
```

**Comment by onyxfish** [comment]
On Travis `pypy` installs version `2.5.0` which does not work with the `regex` module due to the missing implementation of `PyLong_FromUnicode`. I'm unable to test `pypy3` locally, but it definitely works with newer versions like `pypy-4.0.0` and `pypy-5.4.1`. (The latter being what I've been testing against locally.)
