### ISSUE TITLE
No agate.Patchable despite being referenced in docs

### ISSUE THREAD

**Issue by ghisvail** [wireservice/agate#679]
The documentation is referencing `agate.Patchable` in `docs/api/misc.rst`, although it is nowhere to be found in the codebase.

```
/<<PKGBUILDDIR>>/docs/api/misc.rst:5: WARNING: failed to import agate.Patchable
/<<PKGBUILDDIR>>/docs/api/misc.rst:12: WARNING: autodoc: failed to import class 'Patchable' from module 'agate'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/util/inspect.py", line 109, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'agate' has no attribute 'Patchable'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc.py", line 536, in import_object
    obj = self.get_attr(obj, part)
  File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc.py", line 432, in get_attr
    return safe_getattr(obj, name, *defargs)
  File "/usr/lib/python3/dist-packages/sphinx/util/inspect.py", line 125, in safe_getattr
    raise AttributeError(name)
AttributeError: Patchable
```

**Comment by nbedi** [comment]
Nice catch, `agate.Patchable` was deprecated in an earlier release. Thank you!
