### ISSUE TITLE
"last week" often causes datetime inference issue

### ISSUE THREAD

**Issue by myersjustinc** [wireservice/agate#686]
I was attempting to use [csvkit](https://github.com/wireservice/csvkit)'s `csvlook` to view a CSV of template-generated text, and it kept failing with the error `date value out of range`.

Based on the guidance from wireservice/csvkit#822, I passed `--no-inference` and all was well, but I tried to narrow down the problem.

It turns out the phrase `last week` in a cell can cause it to be inferred as a datetime (similar to #653) _and_ raise an exception while doing so. `this week` and `next week` also get inferred as datetimes, but they at least don't raise anything when they do.

Here's the bare minimum example from `csvlook`:

```
$ echo "snippet
last week" | csvlook
date value out of range

$ echo "snippet
last week" | csvlook --no-inference
| snippet   |
| --------- |
| last week |

$ echo "snippet
this week" | csvlook
|    snippet |
| ---------- |
| 0001-01-05 |

$ echo "snippet
next week" | csvlook
|    snippet |
| ---------- |
| 0001-01-08 |
```

Here's the agate-specific demo, based on the fix from #653:

```
>>> agate.Date().cast('next week')
datetime.date(1, 1, 8)
>>> agate.Date().cast('this week')
datetime.date(1, 1, 5)
>>> agate.Date().cast('last week')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/idguser/.virtualenvs/tmp-b84b060a7955a57d/lib/python3.5/site-packages/agate/data_types/date.py", line 75, in cast
    value, ctx = self.parser.parseDT(d, sourceTime=ZERO_DT)
  File "/Users/idguser/.virtualenvs/tmp-b84b060a7955a57d/lib/python3.5/site-packages/parsedatetime/__init__.py", line 1771, in parseDT
    version=version)
  File "/Users/idguser/.virtualenvs/tmp-b84b060a7955a57d/lib/python3.5/site-packages/parsedatetime/__init__.py", line 1845, in parse
    retS, retTime, matched = parseMeth(s, sourceTime)
  File "/Users/idguser/.virtualenvs/tmp-b84b060a7955a57d/lib/python3.5/site-packages/parsedatetime/__init__.py", line 1316, in _partialParseModifier
    chunk2, sourceTime)
  File "/Users/idguser/.virtualenvs/tmp-b84b060a7955a57d/lib/python3.5/site-packages/parsedatetime/__init__.py", line 848, in _evalModifier
    target = start + offset * datetime.timedelta(weeks=1)
OverflowError: date value out of range
```

The inference sometimes can persist even when the `$WORD week` phrase has other stuff around it (which is how I found this), but not always:

```
$ echo "snippet
I had lunch last week." | csvlook
| snippet                |
| ---------------------- |
| I had lunch last week. |

$ echo "snippet
I had lunch last week," | csvlook
date value out of range
```

**Comment by nepella** [comment]
I encountered this with a text field containing the phrase `last day`.

[Pull request No. 720](wireservice/agate#720) appears to fix it for me.

**Comment by jpmckinney** [comment]
#720 is merged, so assuming this is closed.
