### ISSUE TITLE
fails to install with pip in cloud envs due to transitive system dep

### ISSUE THREAD

**Issue by tommyjcarpenter** [wireservice/agate#754]
not sure exactly what to suggest here but just noting a blowup we had this AM

this package depends on: https://github.com/wireservice/agate/blob/master/setup.py#L13

this leads to the transitive problem: https://github.com/ovalhub/pyicu/issues/99

on some cloud machines, where we do *not have apt-get level control*, pyicu does not install due to #99 above, which causes agate to fail, which causes csvkit to fail...

not sure if I have a suggestion at the current moment, though

for us, this bubbles all the way up to `csvkit`; `csvkit->agate->pyicu->boom`

so due to this transitive dependency, this page is basically uninstallable with pip without a `apt-get install` first!

Here is a stack trace, but again we don't have `apt-get` level control here: 
```



2021-03-12T11:04:56.739-05:00 | Collecting PyICU>=2.4.2 (from agate>=1.6.1->csvkit->merq==0.1.9->-r /usr/local/airflow/requirements/requirements.txt (line 4))
  | 2021-03-12T11:04:56.768-05:00 | Downloading https://files.pythonhosted.org/packages/31/46/fa08c8efae2951e67681ec24319f789fc1a74e2096dd74373e34c79319de/PyICU-2.6.tar.gz (233kB)
  | 2021-03-12T11:04:56.799-05:00 | Complete output from command python setup.py egg_info:
  | 2021-03-12T11:04:56.911-05:00 | Package icu-i18n was not found in the pkg-config search path.
  | 2021-03-12T11:04:56.952-05:00 | Perhaps you should add the directory containing `icu-i18n.pc'
  | 2021-03-12T11:04:56.983-05:00 | to the PKG_CONFIG_PATH environment variable
  | 2021-03-12T11:04:57.013-05:00 | No package 'icu-i18n' found
  | 2021-03-12T11:04:57.055-05:00 | (running 'icu-config --version')
  | 2021-03-12T11:04:57.325-05:00 | (running 'pkg-config --modversion icu-i18n')
  | 2021-03-12T11:04:57.359-05:00 | Traceback (most recent call last):
  | 2021-03-12T11:04:57.390-05:00 | File "/tmp/pip-build-t0ktrzsp/PyICU/setup.py", line 63, in <module>
  | 2021-03-12T11:04:57.418-05:00 | ICU_VERSION = os.environ['ICU_VERSION']
  | 2021-03-12T11:04:57.446-05:00 | File "/usr/lib64/python3.7/os.py", line 681, in __getitem__
  | 2021-03-12T11:04:57.474-05:00 | raise KeyError(key) from None
  | 2021-03-12T11:04:57.502-05:00 | KeyError: 'ICU_VERSION'
  | 2021-03-12T11:04:57.535-05:00 |  
  | 2021-03-12T11:04:57.562-05:00 | During handling of the above exception, another exception occurred:
  | 2021-03-12T11:04:57.589-05:00 |  
  | 2021-03-12T11:04:57.620-05:00 | Traceback (most recent call last):
  | 2021-03-12T11:04:58.129-05:00 | File "/tmp/pip-build-t0ktrzsp/PyICU/setup.py", line 66, in <module>
  | 2021-03-12T11:04:58.160-05:00 | ICU_VERSION = check_output(('icu-config', '--version')).strip()
  | 2021-03-12T11:04:58.187-05:00 | File "/tmp/pip-build-t0ktrzsp/PyICU/setup.py", line 19, in check_output
  | 2021-03-12T11:04:58.217-05:00 | return subprocess_check_output(popenargs)
  | 2021-03-12T11:04:58.244-05:00 | File "/usr/lib64/python3.7/subprocess.py", line 411, in check_output
  | 2021-03-12T11:04:58.275-05:00 | **kwargs).stdout
  | 2021-03-12T11:04:58.306-05:00 | File "/usr/lib64/python3.7/subprocess.py", line 488, in run
  | 2021-03-12T11:04:58.338-05:00 | with Popen(*popenargs, **kwargs) as process:
  | 2021-03-12T11:04:58.370-05:00 | File "/usr/lib64/python3.7/subprocess.py", line 800, in __init__
  | 2021-03-12T11:04:58.402-05:00 | restore_signals, start_new_session)
  | 2021-03-12T11:04:58.433-05:00 | File "/usr/lib64/python3.7/subprocess.py", line 1551, in _execute_child
  | 2021-03-12T11:04:59.178-05:00 | raise child_exception_type(errno_num, err_msg, err_filename)
  | 2021-03-12T11:04:59.211-05:00 | FileNotFoundError: [Errno 2] No such file or directory: 'icu-config': 'icu-config'
  | 2021-03-12T11:04:59.243-05:00 |  
  | 2021-03-12T11:04:59.279-05:00 | During handling of the above exception, another exception occurred:
  | 2021-03-12T11:04:59.315-05:00 |  
  | 2021-03-12T11:04:59.348-05:00 | Traceback (most recent call last):
  | 2021-03-12T11:04:59.380-05:00 | File "/tmp/pip-build-t0ktrzsp/PyICU/setup.py", line 69, in <module>
  | 2021-03-12T11:04:59.413-05:00 | ICU_VERSION = check_output(('pkg-config', '--modversion', 'icu-i18n')).strip()
  | 2021-03-12T11:04:59.448-05:00 | File "/tmp/pip-build-t0ktrzsp/PyICU/setup.py", line 19, in check_output
  | 2021-03-12T11:04:59.483-05:00 | return subprocess_check_output(popenargs)
  | 2021-03-12T11:04:59.519-05:00 | File "/usr/lib64/python3.7/subprocess.py", line 411, in check_output
  | 2021-03-12T11:05:00.274-05:00 | **kwargs).stdout
  | 2021-03-12T11:05:00.307-05:00 | File "/usr/lib64/python3.7/subprocess.py", line 512, in run
  | 2021-03-12T11:05:00.341-05:00 | output=stdout, stderr=stderr)
  | 2021-03-12T11:05:00.375-05:00 | subprocess.CalledProcessError: Command '('pkg-config', '--modversion', 'icu-i18n')' returned non-zero exit status 1.
  | 2021-03-12T11:05:00.407-05:00 |  
  | 2021-03-12T11:05:00.443-05:00 | During handling of the above exception, another exception occurred:
  | 2021-03-12T11:05:00.473-05:00 |  
  | 2021-03-12T11:05:00.501-05:00 | Traceback (most recent call last):
  | 2021-03-12T11:05:00.534-05:00 | File "<string>", line 1, in <module>
  | 2021-03-12T11:05:00.563-05:00 | File "/tmp/pip-build-t0ktrzsp/PyICU/setup.py", line 74, in <module>
  | 2021-03-12T11:05:00.595-05:00 | ''')
  | 2021-03-12T11:05:00.834-05:00 | RuntimeError:
  | 2021-03-12T11:05:00.864-05:00 | Please install pkg-config on your system or set the ICU_VERSION environment
  | 2021-03-12T11:05:00.893-05:00 | variable to the version of ICU you have installed.
  | 2021-03-12T11:05:00.917-05:00 |  


```

**Comment by jpmckinney** [comment]
I've made a commit that removes the PyICU dependency. Let me know if it works, and I'll make a release.
