### ISSUE TITLE
Default string output of TableSet with multiple layers of nesting throws `AttributeError: 'TableSet' object has no attribute 'rows'`

### ISSUE THREAD

**Issue by vergenzt** [wireservice/agate#765]
Example below. I encountered this while exploring a dataset in an ipdb debugging session ([debugging a dbt macro](https://docs.getdbt.com/reference/dbt-jinja-functions/debug-method)). For some reason ipdb wasn't showing me the full stack traces for errors -- just the exception type and description.

So the only output I got looked like this:
```
ipdb> mytable.group_by('col1').group_by('col2')
*** AttributeError: 'TableSet' object has no attribute 'rows'
ipdb> _
```

making this issue more confusing than it may have otherwise been.

Note, now that I understand this is simply an issue with the string output on the REPL and _not_ an issue with the underlying data (and I can still save it to disk), this issue does not block me.

## Example to reproduce

**Input**:
```
>>> import agate
>>> mytable = agate.Table([('foo', 'FOO', 1), ('foo', 'FOO', 2), ('bar', 'BOZ', 1), ('bar', 'BAZ', 2), ('bar', 'BIZ')])
<stdin>:1: RuntimeWarning: Column names not specified. "('a', 'b', 'c')" will be used as names.
```

**Actual string output**:
```
>>> mytable.group_by('a').group_by('b')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../.venv/lib/python3.8/site-packages/agate/mapped_sequence.py", line 87, in __repr__
    return self.__str__()
  File ".../.venv/lib/python3.8/site-packages/agate/tableset/__init__.py", line 91, in __str__
    self.print_structure(output=structure)
  File ".../.venv/lib/python3.8/site-packages/agate/tableset/print_structure.py", line 24, in print_structure
    type_column = [str(len(table.rows)) for key, table in self.items()[0:max_length]]
  File ".../.venv/lib/python3.8/site-packages/agate/tableset/print_structure.py", line 24, in <listcomp>
    type_column = [str(len(table.rows)) for key, table in self.items()[0:max_length]]
AttributeError: 'TableSet' object has no attribute 'rows'
```

**JSON output for clarity**:
```
>>> mytable.group_by('a').group_by('b').to_json('/dev/stdout', nested=True)
{"foo": {"FOO": [{"a": "foo", "b": "FOO", "c": 1.0}, {"a": "foo", "b": "FOO", "c": 2.0}]}, "bar": {"BOZ": [{"a": "bar", "b": "BOZ", "c": 1.0}], "BAZ": [{"a": "bar", "b": "BAZ", "c": 2.0}], "BIZ": [{"a": "bar", "b": "BIZ", "c": null}]}}
```

**Expected string output**:

???

(I have no ideas here other than "probably not an exception". 🙂  Figured I'd still go ahead and share.)

**Comment by jpmckinney** [comment]
Thank you for reporting!

The issue was that group_by – uniquely – returns a TableSet instead of a Table. Calling group_by a second time yielded a TableSet containing TableSets (instead of directly containing Tables), causing the error.

**Comment by jpmckinney** [comment]
Ah, my solution worked for group_by, but it messed up pivot (which calls group_by and aggregate) and aggregate (which contains logic for nested table sets).

**Comment by jpmckinney** [comment]
Does this make any sense for that input?

```
| table   | rows |
| ------- | ---- |
| foo.FOO | 2    |
| bar.BOZ | 1    |
| bar.BAZ | 1    |
| bar.BIZ | 1    |
```

**Comment by jpmckinney** [comment]
The patch:

```diff
diff --git a/agate/tableset/print_structure.py b/agate/tableset/print_structure.py
index e842249..0ceb929 100644
--- a/agate/tableset/print_structure.py
+++ b/agate/tableset/print_structure.py
@@ -2,6 +2,15 @@ import sys
 
 from agate.data_types import Text
 from agate.table import Table
+from agate.tableset import TableSet
+
+
+def _items(key, value):
+    if isinstance(value, TableSet):
+        for k, v in value.items():
+            yield from _items(key + (k,), v)
+    else:
+        yield key, value
 
 
 def print_structure(self, max_rows=20, output=sys.stdout):
@@ -16,10 +25,11 @@ def print_structure(self, max_rows=20, output=sys.stdout):
     :returns:
         None
     """
-    max_length = min(len(self.items()), max_rows)
+    items = list(_items((), self))
+    max_length = min(len(items), max_rows)
 
-    name_column = self.keys()[0:max_length]
-    type_column = [str(len(table.rows)) for key, table in self.items()[0:max_length]]
+    name_column = ['.'.join(key) for key, value in items][0:max_length]
+    type_column = [str(len(table.rows)) for key, table in items[0:max_length]]
     rows = zip(name_column, type_column)
     column_names = ['table', 'rows']
     text = Text()
```
